root: true
extends:
  - "@pinetwork-js"
  - prettier
plugins:
  - prettier
  - tsdoc
rules:
  prettier/prettier: error
  tsdoc/syntax: warn
env:
  node: true
  es2020: true
parserOptions:
  project: tsconfig.json
